"""Song dataset for the recommender simulation.

Each song is a plain dict so the rest of the system stays framework-free.
Core attributes (genre, mood, energy, tempo, era) are the ones a real
streaming service would derive from audio analysis + editorial tagging.
The extra attributes (popularity, release_decade, mood_tags, danceability,
acousticness) were added in a second pass to give the scoring function more
signal to work with -- see ai_interactions.md for how that pass was done.
"""

SONGS = [
    {
        "title": "Midnight Bassline",
        "artist": "Neon Circuit",
        "genre": "edm",
        "mood": "euphoric",
        "energy": 9,
        "tempo": 128,
        "era": "2020s",
        "popularity": 78,
        "release_decade": 2020,
        "mood_tags": ["euphoric", "driving", "anthemic"],
        "danceability": 9,
        "acousticness": 1,
    },
    {
        "title": "Warehouse Lights",
        "artist": "Kito Waves",
        "genre": "edm",
        "mood": "energetic",
        "energy": 8,
        "tempo": 124,
        "era": "2010s",
        "popularity": 65,
        "release_decade": 2010,
        "mood_tags": ["energetic", "pulsing"],
        "danceability": 8,
        "acousticness": 1,
    },
    {
        "title": "Corner Store Freestyle",
        "artist": "Dre Larkin",
        "genre": "hip-hop",
        "mood": "confident",
        "energy": 7,
        "tempo": 95,
        "era": "2020s",
        "popularity": 82,
        "release_decade": 2020,
        "mood_tags": ["confident", "gritty", "braggadocious"],
        "danceability": 7,
        "acousticness": 2,
    },
    {
        "title": "Trap Door",
        "artist": "Lil Ember",
        "genre": "hip-hop",
        "mood": "aggressive",
        "energy": 8,
        "tempo": 140,
        "era": "2020s",
        "popularity": 88,
        "release_decade": 2020,
        "mood_tags": ["aggressive", "dark", "hard-hitting"],
        "danceability": 6,
        "acousticness": 1,
    },
    {
        "title": "Rearview Mirror",
        "artist": "Dre Larkin",
        "genre": "hip-hop",
        "mood": "reflective",
        "energy": 4,
        "tempo": 82,
        "era": "2010s",
        "popularity": 54,
        "release_decade": 2010,
        "mood_tags": ["reflective", "nostalgic"],
        "danceability": 4,
        "acousticness": 3,
    },
    {
        "title": "Porch Light",
        "artist": "Maren Holt",
        "genre": "acoustic",
        "mood": "calm",
        "energy": 2,
        "tempo": 76,
        "era": "2020s",
        "popularity": 41,
        "release_decade": 2020,
        "mood_tags": ["calm", "intimate", "warm"],
        "danceability": 2,
        "acousticness": 9,
    },
    {
        "title": "Quiet Hollow",
        "artist": "Sable Wren",
        "genre": "acoustic",
        "mood": "melancholy",
        "energy": 2,
        "tempo": 68,
        "era": "2010s",
        "popularity": 33,
        "release_decade": 2010,
        "mood_tags": ["melancholy", "sparse"],
        "danceability": 1,
        "acousticness": 10,
    },
    {
        "title": "Kitchen Table Talk",
        "artist": "Maren Holt",
        "genre": "acoustic",
        "mood": "tender",
        "energy": 3,
        "tempo": 80,
        "era": "2020s",
        "popularity": 47,
        "release_decade": 2020,
        "mood_tags": ["tender", "conversational"],
        "danceability": 2,
        "acousticness": 8,
    },
    {
        "title": "Rooftop Static",
        "artist": "The Aftertones",
        "genre": "indie-rock",
        "mood": "wistful",
        "energy": 5,
        "tempo": 110,
        "era": "2010s",
        "popularity": 58,
        "release_decade": 2010,
        "mood_tags": ["wistful", "jangly"],
        "danceability": 5,
        "acousticness": 5,
    },
    {
        "title": "Static Bloom",
        "artist": "The Aftertones",
        "genre": "indie-rock",
        "mood": "hopeful",
        "energy": 6,
        "tempo": 118,
        "era": "2020s",
        "popularity": 61,
        "release_decade": 2020,
        "mood_tags": ["hopeful", "bright"],
        "danceability": 5,
        "acousticness": 4,
    },
    {
        "title": "Basement Tapes Vol. 2",
        "artist": "Corvid Youth",
        "genre": "indie-rock",
        "mood": "restless",
        "energy": 7,
        "tempo": 132,
        "era": "2020s",
        "popularity": 44,
        "release_decade": 2020,
        "mood_tags": ["restless", "raw"],
        "danceability": 5,
        "acousticness": 3,
    },
    {
        "title": "Chrome Heart",
        "artist": "Vela Sun",
        "genre": "pop",
        "mood": "euphoric",
        "energy": 8,
        "tempo": 120,
        "era": "2020s",
        "popularity": 91,
        "release_decade": 2020,
        "mood_tags": ["euphoric", "shiny", "anthemic"],
        "danceability": 8,
        "acousticness": 2,
    },
    {
        "title": "Slow Dance, Fast City",
        "artist": "Vela Sun",
        "genre": "pop",
        "mood": "romantic",
        "energy": 5,
        "tempo": 100,
        "era": "2020s",
        "popularity": 87,
        "release_decade": 2020,
        "mood_tags": ["romantic", "glossy"],
        "danceability": 6,
        "acousticness": 3,
    },
    {
        "title": "Summer Static",
        "artist": "Coral June",
        "genre": "pop",
        "mood": "happy",
        "energy": 7,
        "tempo": 112,
        "era": "2010s",
        "popularity": 73,
        "release_decade": 2010,
        "mood_tags": ["happy", "breezy"],
        "danceability": 7,
        "acousticness": 3,
    },
    {
        "title": "Blue Static Radio",
        "artist": "Coral June",
        "genre": "pop",
        "mood": "nostalgic",
        "energy": 4,
        "tempo": 90,
        "era": "2010s",
        "popularity": 69,
        "release_decade": 2010,
        "mood_tags": ["nostalgic", "wistful"],
        "danceability": 4,
        "acousticness": 4,
    },
    {
        "title": "Low End Theory Redux",
        "artist": "Basswell",
        "genre": "hip-hop",
        "mood": "chill",
        "energy": 3,
        "tempo": 86,
        "era": "1990s",
        "popularity": 39,
        "release_decade": 1990,
        "mood_tags": ["chill", "smooth", "jazzy"],
        "danceability": 5,
        "acousticness": 4,
    },
    {
        "title": "Voltage Church",
        "artist": "Neon Circuit",
        "genre": "edm",
        "mood": "intense",
        "energy": 10,
        "tempo": 150,
        "era": "2020s",
        "popularity": 70,
        "release_decade": 2020,
        "mood_tags": ["intense", "relentless"],
        "danceability": 9,
        "acousticness": 1,
    },
    {
        "title": "Faded Denim",
        "artist": "Sable Wren",
        "genre": "acoustic",
        "mood": "nostalgic",
        "energy": 3,
        "tempo": 72,
        "era": "1990s",
        "popularity": 28,
        "release_decade": 1990,
        "mood_tags": ["nostalgic", "dusty"],
        "danceability": 2,
        "acousticness": 9,
    },
    {
        "title": "Midwest Emo Kid",
        "artist": "Corvid Youth",
        "genre": "indie-rock",
        "mood": "yearning",
        "energy": 6,
        "tempo": 138,
        "era": "2010s",
        "popularity": 36,
        "release_decade": 2010,
        "mood_tags": ["yearning", "frantic"],
        "danceability": 4,
        "acousticness": 3,
    },
    {
        "title": "Gold Rush Hour",
        "artist": "Basswell",
        "genre": "hip-hop",
        "mood": "confident",
        "energy": 6,
        "tempo": 98,
        "era": "1990s",
        "popularity": 45,
        "release_decade": 1990,
        "mood_tags": ["confident", "smooth"],
        "danceability": 6,
        "acousticness": 3,
    },
]


def load_songs():
    """Return a fresh copy of the song dataset (list of dicts)."""
    return [dict(song) for song in SONGS]
